### ISSUE TITLE
fl_load_module_examples function name

### ISSUE THREAD

**Issue by jontrujillo** [bacoords/cb-custom-module#1]
I noticed — because I made the same mistake — that you are using the function name from the BB Custom module example to load up your modules. I tried activating your modules after activating some that I created and my WP Install errored out and wouldn't activate your plugin. I renamed my loading function and thought I'd give you a heads up. Thank's for these awesome modules!

**Comment by jatacid** [comment]
Hi, what function name?

On Tue, Aug 23, 2016 at 3:13 AM, Jonathan Trujillo <notifications@github.com

**Comment by bacoords** [comment]
The main function that loads the modules: `fl_load_module_examples()`

Good catch! I'll post an update ASAP.

**Comment by jontrujillo** [comment]
👍  sorry, I should have been clearer. Thanks for taking care of it!
