### ISSUE TITLE
Link List does not output any text after updating Beaver Builder plugin to 2.2.0.3

### ISSUE THREAD

**Issue by chrisfullman** [bacoords/cb-custom-module#4]
It appears as if CB Custom Modules' Link List is no longer working as expected with the latest version of the Beaver Builder plugin (2.2.0.3).

Several of my Link List components now show up as empty list items (when no icon is selected) or only has the icon without any of the label or media metadata included.

### Steps to Reproduce
1. Update Beaver Builder plugin to 2.2.0.3
2. View existing Link List module or add Link List module and confirm items have either a label populated with/without a media file selected
3. View the page and find a list without text being output in each list item's HTML (see screenshot)

### Troubleshooting Attempted
1. Cleared Beaver Builder cache
2. Cleared hosting vendor cache
3. Edited module to confirm populated label text and/or

### Screenshots
![screen shot 2019-01-09 at 11 47 02 am](https://user-images.githubusercontent.com/46894/50914423-837ddf80-1404-11e9-8e0f-86307cb26a5d.png)
![screen shot 2019-01-09 at 11 50 03 am](https://user-images.githubusercontent.com/46894/50914612-f424fc00-1404-11e9-80d4-3814e78450da.png)

**Comment by bacoords** [comment]
Thanks for the very detailed bug report. Very helpful! I've tracked the issue down and fixed it in the 1.6.1 update. 

https://github.com/bacoords/cb-custom-modules/commit/1f6548300634c3748009936454471cd4fd8c5386
